const Pictures2 = [
    {"src" : "../Pictures2/PFK_501.jpeg", "alt" : "Photo 1"},
    {"src" : "../Pictures2/PFK_502.jpeg", "alt" : "Photo 2"},
    {"src" : "../Pictures2/PFK_503.jpeg", "alt" : "Photo 3"},
    {"src" : "../Pictures2/PFK_504.jpeg", "alt" : "Photo 4"},
    {"src" : "../Pictures2/PFK_505.jpeg", "alt" : "Photo 5"},
    {"src" : "../Pictures2/PFK_506.jpeg", "alt" : "Photo 6"},
    {"src" : "../Pictures2/PFK_507.jpeg", "alt" : "Photo 7"},
    {"src" : "../Pictures2/PFK_508.jpeg", "alt" : "Photo 8"},
    {"src" : "../Pictures2/PFK_509.jpeg", "alt" : "Photo 9"},
    {"src" : "../Pictures2/PFK_510.jpeg", "alt" : "Photo 10"},
    {"src" : "../Pictures2/PFK_511.jpeg", "alt" : "Photo 11"},
    {"src" : "../Pictures2/PFK_512.jpeg", "alt" : "Photo 12"},
    {"src" : "../Pictures2/PFK_513.jpeg", "alt" : "Photo 13"},
    {"src" : "../Pictures2/PFK_514.jpeg", "alt" : "Photo 14"},
    {"src" : "../Pictures2/PFK_515.jpeg", "alt" : "Photo 15"},
    {"src" : "../Pictures2/PFK_516.jpeg", "alt" : "Photo 16"},
    {"src" : "../Pictures2/PFK_517.jpeg", "alt" : "Photo 17"},
    {"src" : "../Pictures2/PFK_518.jpeg", "alt" : "Photo 18"},
    {"src" : "../Pictures2/PFK_519.jpeg", "alt" : "Photo 19"},
    {"src" : "../Pictures2/PFK_520.jpeg", "alt" : "Photo 20"},
    {"src" : "../Pictures2/PFK_521.jpeg", "alt" : "Photo 21"},
    {"src" : "../Pictures2/PFK_522.jpeg", "alt" : "Photo 22"},
    {"src" : "../Pictures2/PFK_523.jpeg", "alt" : "Photo 23"},
    {"src" : "../Pictures2/PFK_524.jpeg", "alt" : "Photo 24"},
    {"src" : "../Pictures2/PFK_525.jpeg", "alt" : "Photo 25"},
    {"src" : "../Pictures2/PFK_526.jpeg", "alt" : "Photo 26"},
    {"src" : "../Pictures2/PFK_527.jpeg", "alt" : "Photo 27"},
    {"src" : "../Pictures2/PFK_528.jpeg", "alt" : "Photo 28"},
    {"src" : "../Pictures2/PFK_529.jpeg", "alt" : "Photo 29"},
    {"src" : "../Pictures2/PFK_530.jpeg", "alt" : "Photo 30"},

]
export default Pictures2;