const Pictures3 = [
    {"src" : "../Pictures3/ETC_501.jpeg", "alt" : "Photo 1"},
    {"src" : "../Pictures3/ETC_502.jpeg", "alt" : "Photo 2"},
    {"src" : "../Pictures3/ETC_503.jpeg", "alt" : "Photo 3"},
    {"src" : "../Pictures3/ETC_504.jpeg", "alt" : "Photo 4"},
    {"src" : "../Pictures3/ETC_505.jpeg", "alt" : "Photo 5"},
    {"src" : "../Pictures3/ETC_506.jpeg", "alt" : "Photo 6"},
    {"src" : "../Pictures3/ETC_507.jpeg", "alt" : "Photo 7"},
    {"src" : "../Pictures3/ETC_508.jpeg", "alt" : "Photo 8"},
    {"src" : "../Pictures3/ETC_509.jpeg", "alt" : "Photo 9"},
    {"src" : "../Pictures3/ETC_510.jpeg", "alt" : "Photo 10"},
    {"src" : "../Pictures3/ETC_511.jpeg", "alt" : "Photo 11"},
    {"src" : "../Pictures3/ETC_512.jpeg", "alt" : "Photo 12"},
    {"src" : "../Pictures3/ETC_513.jpeg", "alt" : "Photo 13"},
    {"src" : "../Pictures3/ETC_514.jpeg", "alt" : "Photo 14"},
    {"src" : "../Pictures3/ETC_515.jpeg", "alt" : "Photo 15"},
    {"src" : "../Pictures3/ETC_516.jpeg", "alt" : "Photo 16"},
    {"src" : "../Pictures3/ETC_517.jpeg", "alt" : "Photo 17"},
    {"src" : "../Pictures3/ETC_518.jpeg", "alt" : "Photo 18"},
    {"src" : "../Pictures3/ETC_519.jpeg", "alt" : "Photo 19"},
    {"src" : "../Pictures3/ETC_520.jpeg", "alt" : "Photo 20"},
    {"src" : "../Pictures3/ETC_521.jpeg", "alt" : "Photo 21"},
    {"src" : "../Pictures3/ETC_522.jpeg", "alt" : "Photo 22"},
    {"src" : "../Pictures3/ETC_523.jpeg", "alt" : "Photo 23"},
    {"src" : "../Pictures3/ETC_524.jpeg", "alt" : "Photo 24"},
    {"src" : "../Pictures3/ETC_525.jpeg", "alt" : "Photo 25"},
    {"src" : "../Pictures3/ETC_526.jpeg", "alt" : "Photo 26"},
    {"src" : "../Pictures3/ETC_527.jpeg", "alt" : "Photo 27"},
    {"src" : "../Pictures3/ETC_528.jpeg", "alt" : "Photo 28"},
    {"src" : "../Pictures3/ETC_529.jpeg", "alt" : "Photo 29"},
    {"src" : "../Pictures3/ETC_530.jpeg", "alt" : "Photo 30"},
];

export default Pictures3;